audit_header: false
title: Libertyville Real Estate Video Blog with Jan Leasure
description: >-
  Our mission at Diamond Residential Mortgage is to be your best resource for
  Libertyville real estate advice. Whether you are a buyer, seller, or investor,
  our team of professionals can answer any questions you might have about real
  estate. If you are looking to buy or sell a home, you can get all the
  information and the latest updates, tips, and tricks from The Diamond
  Residential Mortgage, your professional Libertyville Real Estate Agents.
show_custom_links: false
custom_links:
  - title:
    url:
show_custom_links_new_tab: false
custom_links_new_tab:
  - title:
    url:
client:
  name: Jan Leasure | NMLS#213431
  title:
  license_number:
  about_markdown: >-
    Jan Leasure has done it all. You may know her as your former teacher (Jack
    Benny Junior High School, Waukegan), as your college instructor (Columbia
    College), as a journalist (contributing editor to Mortgage Broker Magazine,
    Mortgage Originator Magazine, or the money-saving $uper $aver), or as your
    mortgage banker. She entered the field of mortgage banking in 1996 because
    it gave her the opportunity to do several things she loves: help others,
    teach, and solve problems. Jan accepted her current position as Division
    President of Diamond Residential Mortgage, Libertyville for three reasons:
    Their commitment to personalized customer service, their determination to
    ensuring that all loans close with integrity, and the great support and
    positive attitude that the company emanates through every employee.
  brand: Diamond Residential Mortgage
  brokerage:
  market: Libertyville
  address: 533 N. Milwaukee Avenue Libertyville, IL 60048
  phone: 847-362-1335
  phone_type:
  phone2:
  phone2_type:
  email: Jan.Leasure@drmconline.com
  url: https://www.LakeCountyLoanGoddess.com
CTAs:
  first_CTA_text: 847-362-1335
  first_CTA_URL: tel:1-847-362-1335
sidebar_CTA:
  - CTA_image_path: /img/cta-images/001.jpg
    CTA_title: Get Pre-Approved in Seconds!
    CTA_text: >-
      Fill out this document and print it off to fill out all the information to
      get pre-approved
    CTA_link_text: Click Here
    CTA_url: https://www.scribd.com/document/164040884/Get-Pre-Approved-in-Seconds
lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: /img/lender-headshot.jpg
  logo_path: /img/lender-logo.png
  name:
  license_number:
  company:
  company_license_number:
  phone:
  email:
  url:
socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/diamondresidentialmortgage
  linkedin_url: https://www.linkedin.com/pub/jan-leasure/a/832/195
  youtube_url: https://www.youtube.com/channel/UCHUJp7RcbpuYrd6-o8hLMWw
  twitter_url: https://twitter.com/Diamond_Homes
  instagram_url:
  pinterest_url:
  zillow_url: http://www.zillow.com/profile/LOANGODDESS1/Reviews/#
  trulia_url: >-
    http://www.trulia.com/profile/jan-leasure-mortgage-broker-or-lender-libertyville-il-8196082/overview
  yelp_url: >-
    http://www.yelp.com/biz/diamond-residential-mortgage-corporation-libertyville
  podcast_url:
podcast:
  title: Libertyville Real Estate Podcast with Jan Leasure
  categories: Education
  image: /img/podcast.jpg
  subtitle: >-
    Learn all the tips, tricks and more for buyers and sellers in the
    Libertyville Area Real Estate Market
  description: >-
    If you are looking to buy or sell a home, get all the information and the
    latest updates, tips, and tricks from Diamond Residential Mortgage - your
    professional Libertyville Real Estate Agents.
  keywords: >-
    Real Estate for sale, Real Estate agents, top real estate agents, local real
    estate agents, find a real estate agent, houses for sale in Libertyville,
    home selling tips, home for sale, home buying, home buying process, property
    finder, property search, property, real estate market, estate agent,
    realestate, real estate listings, buying a house, homes for sale, mls, home
    buyer
  author: Jan Leasure
images:
  client_headshot_path: /img/headshot.png
  hero_logo_path: /img/logo.png
  logo_width_number: 40
  hero_text: Libertyville Real Estate Video Blog
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
  post_cta_image: /img/home-value.jpg
  post_cta_image2: /img/home-search.jpg
site_colors:
  brand_color: '#005097'
  theme_color: '#a8a7a9'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'
header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: white
buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: rgba(0, 0, 0, 0)
  secondary_button_text_color: '#ffffff'
